<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Automation-win" name="scripts.RejectScheduleAcceptFunctionalityTest" tests="6" failures="1" timestamp="2023-12-14T14:35:55 IST" time="325.319" errors="0">
  <testcase name="Creating_Audit_Type_Test" time="199.758" classname="scripts.RejectScheduleAcceptFunctionalityTest"/>
  <system-out/>
  <testcase name="Auditee_Admin_Configuration_Test" time="16.147" classname="scripts.RejectScheduleAcceptFunctionalityTest"/>
  <system-out/>
  <testcase name="Creating_Audit_Schedule_Test" time="20.126" classname="scripts.RejectScheduleAcceptFunctionalityTest"/>
  <system-out/>
  <testcase name="Rejecting_Schedule_Test" time="20.659" classname="scripts.RejectScheduleAcceptFunctionalityTest"/>
  <system-out/>
  <testcase name="Request_Accept_Test_By_Admin" time="47.652" classname="scripts.RejectScheduleAcceptFunctionalityTest"/>
  <system-out/>
  <testcase name="Accepted_Request_Should_Not_Be_Show_For_The_Auditor_Test" time="20.977" classname="scripts.RejectScheduleAcceptFunctionalityTest">
    <failure type="java.lang.AssertionError" message="Accept Button is Displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Accept Button is Displayed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at scripts.RejectScheduleAcceptFunctionalityTest.Accepted_Request_Should_Not_Be_Show_For_The_Auditor_Test(RejectScheduleAcceptFunctionalityTest.java:676)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Accepted_Request_Should_Not_Be_Show_For_The_Auditor_Test -->
  <system-out/>
</testsuite> <!-- scripts.RejectScheduleAcceptFunctionalityTest -->
